//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knights.UISystem {


    public sealed class ScreenIds {

        public const string CarSelectionPanel = "CarSelectionPanel";

        public const string CharacterSelectionPanel = "CharacterSelectionPanel";

        public const string GoalsPanel = "GoalsPanel";

        public const string InventoryCelebrationPanel = "InventoryCelebrationPanel";

        public const string LeaderBoardsPanel = "LeaderBoardsPanel";

        public const string MainMenuPanel = "MainMenuPanel";

        public const string MysteryBoxPanelShop = "MysteryBoxPanelShop";

        public const string MysteryBoxPanel = "MysteryBoxPanelDailyReward";

        public const string MysteryBoxPanelDailyReward = "MysteryBoxPanelDailyReward";

        public const string PurchaseSuccess = "PurchaseSuccess";

        public const string QuitPrompt = "QuitPrompt";

        public const string QuitPromptGame = "QuitPromptGame";

        public const string ResourcesNotAvailable = "ResourcesNotAvailable";

        public const string Settings = "Settings";

        public const string ShopPanel = "ShopPanel";

        public const string GameOverPanel = "GameOverPanel";

        public const string HighScoreScreen = "HighScoreScreen";

        public const string HUDPanel = "HUDPanel";

        public const string PausePanel = "PausePanel";

        public const string PauseSettings = "PauseSettings";

        public const string DailyGoalsPopUp = "DailyGoalsPopUp";

        public const string DiamondStashCompletePopUp = "DiamondStashCompletePopUp";

        public const string DiamondStashesPopUp = "DiamondStashesPopUp";

        public const string HighScorePopUp = "HighScorePopUp";

        public const string RevivePanel = "RevivePanel";

        public const string ShopBundlePanel = "ShopBundlePanel";

        public const string ShopBundlePanelBoost = "ShopBundlePanelBoost";

        public const string TapToPlayButton = "TapToPlayButton";

        public const string RewardPanel = "RewardPanel";

        public const string OpenMysteryBoxScreen = "OpenMysteryBoxScreen";

        public const string AdIsLoading = "AdIsLoading";

        public const string AdIsLoadingBeforeCutScene = "AdIsLoadingBeforeCutScene";

        public const string CarAvailablePopup = "CarAvailablePopup";

        public const string CarAvailableInGamePanel = "CarAvailableInGamePanel";

        public const string ForceUpdatePrompt = "ForceUpdatePrompt";

        public const string GetReadyPanel = "GetReadyPanel";

        public const string LeaderBoardAwardAvailable = "LeaderBoardAwardAvailable";

        public const string FaceBookLoginPopup = "FaceBookLoginPopup";

        public const string CrossPromoADSScreen = "CrossPromoADSScreen";

        public const string PanelAppRating = "PanelAppRating";

        public const string RemoveADS_IAP_Popup = "RemoveADS_IAP_Popup";

        public const string UnlockCars_IAP_Popup = "UnlockCars_IAP_Popup";

        public const string GamePlayPowerUpADScreen = "GamePlayPowerUpADScreen";

        public const string CarUnlockedScreen = "CarUnlockedScreen";

        public const string LimitedTimeOffer_01 = "LimitedTimeOffer_01";

        public const string LimitedTimeOffer_02 = "LimitedTimeOffer_02";

        public const string LimitedTimeOffer_03 = "LimitedTimeOffer_03";

        public const string CharacterUnlockedScreen = "CharacterUnlockedScreen";

        public const string UnlockCarsAndCharacters = "UnlockCarsAndCharacters";

        public const string UnlockCharacters_IAP_Popup = "UnlockCharacters_IAP_Popup";

        public const string InformationPanelScreen = "InformationPanelScreen";

        public const string TutorialTextHintPanel = "TutorialTextHintPanel";
        //public const string Profile = "Profile";
    }
}
