// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_full_destructor_level_3 = "CgkIg52m0JQYEAIQJA"; // <GPGSID>
        public const string achievement_always_prepared_level_1 = "CgkIg52m0JQYEAIQEQ"; // <GPGSID>
        public const string achievement_always_prepared_level_2 = "CgkIg52m0JQYEAIQGw"; // <GPGSID>
        public const string achievement_always_prepared_level_3 = "CgkIg52m0JQYEAIQJQ"; // <GPGSID>
        public const string leaderboard_playerlevel = "CgkIg52m0JQYEAIQKg"; // <GPGSID>
        public const string achievement_extreme_power_level_1 = "CgkIg52m0JQYEAIQDA"; // <GPGSID>
        public const string achievement_extreme_power_level_2 = "CgkIg52m0JQYEAIQFg"; // <GPGSID>
        public const string achievement_king_of_the_road_level_2 = "CgkIg52m0JQYEAIQFw"; // <GPGSID>
        public const string achievement_full_power_level_1 = "CgkIg52m0JQYEAIQEg"; // <GPGSID>
        public const string achievement_full_power_level_2 = "CgkIg52m0JQYEAIQHA"; // <GPGSID>
        public const string achievement_full_power_level_3 = "CgkIg52m0JQYEAIQJg"; // <GPGSID>
        public const string leaderboard_total_distance_covered = "CgkIg52m0JQYEAIQJw"; // <GPGSID>
        public const string achievement_smash_runner_level_1 = "CgkIg52m0JQYEAIQCQ"; // <GPGSID>
        public const string achievement_smash_runner_level_2 = "CgkIg52m0JQYEAIQEw"; // <GPGSID>
        public const string achievement_smash_runner_level_3 = "CgkIg52m0JQYEAIQHQ"; // <GPGSID>
        public const string achievement_collect_10000_coins = "CgkIg52m0JQYEAIQAQ"; // <GPGSID>
        public const string achievement_collect_700000_coins = "CgkIg52m0JQYEAIQBg"; // <GPGSID>
        public const string achievement_full_destructor_level_2 = "CgkIg52m0JQYEAIQGg"; // <GPGSID>
        public const string achievement_full_destructor_level_1 = "CgkIg52m0JQYEAIQEA"; // <GPGSID>
        public const string achievement_extreme_power_level_3 = "CgkIg52m0JQYEAIQIA"; // <GPGSID>
        public const string achievement_collect_300000_coins = "CgkIg52m0JQYEAIQBQ"; // <GPGSID>
        public const string leaderboard_total_coins_collected = "CgkIg52m0JQYEAIQKA"; // <GPGSID>
        public const string achievement_collect_100000_coins = "CgkIg52m0JQYEAIQBA"; // <GPGSID>
        public const string achievement_rush_driver_level_1 = "CgkIg52m0JQYEAIQCw"; // <GPGSID>
        public const string achievement_rush_driver_level_2 = "CgkIg52m0JQYEAIQFQ"; // <GPGSID>
        public const string achievement_collect_60000_coins = "CgkIg52m0JQYEAIQAw"; // <GPGSID>
        public const string achievement_elite_rider_level_1 = "CgkIg52m0JQYEAIQDw"; // <GPGSID>
        public const string achievement_elite_rider_level_3 = "CgkIg52m0JQYEAIQIw"; // <GPGSID>
        public const string achievement_elite_rider_level_2 = "CgkIg52m0JQYEAIQGQ"; // <GPGSID>
        public const string achievement_most_dangerous_level_3 = "CgkIg52m0JQYEAIQIg"; // <GPGSID>
        public const string leaderboard_distancecovered = "CgkIg52m0JQYEAIQKQ"; // <GPGSID>
        public const string achievement_collect_30000_coins = "CgkIg52m0JQYEAIQAg"; // <GPGSID>
        public const string achievement_rush_driver_level_3 = "CgkIg52m0JQYEAIQHw"; // <GPGSID>
        public const string achievement_most_dangerous_level_1 = "CgkIg52m0JQYEAIQDg"; // <GPGSID>
        public const string achievement_most_dangerous_level_2 = "CgkIg52m0JQYEAIQGA"; // <GPGSID>
        public const string leaderboard_life_time_coins_collection = "CgkIg52m0JQYEAIQCA"; // <GPGSID>
        public const string achievement_king_of_the_road_level_3 = "CgkIg52m0JQYEAIQIQ"; // <GPGSID>
        public const string achievement_unstoppable_level_2 = "CgkIg52m0JQYEAIQFA"; // <GPGSID>
        public const string achievement_unstoppable_level_3 = "CgkIg52m0JQYEAIQHg"; // <GPGSID>
        public const string achievement_king_of_the_road_level_1 = "CgkIg52m0JQYEAIQDQ"; // <GPGSID>
        public const string achievement_collect_1200000_coins = "CgkIg52m0JQYEAIQBw"; // <GPGSID>
        public const string achievement_unstoppable_level_1 = "CgkIg52m0JQYEAIQCg"; // <GPGSID>

}

